const mongoose = require('mongoose');

const orderSchema = mongoose.Schema({
    orderItems: [{      // With the square brackets its specifies multiple items on an array
        type: mongoose.Schema.Types.ObjectId, //This is tha way to link the orderItems ID from the table of orderItems
        ref: 'OrderItem',
        required: true
    }],
    shippingAddress1: {
        type: String,
        required: true
    },
    shippingAddress2: {
        type: String
    },
    city: {
        type: String,
        required: true
    },
    zip: {
        type: String,
        required: true
    },
    country: {
        type: String,
        required: true
    },
    phone: {
        type: String,
        required: true
    },
    status: {
        type: String,
        required: true,
        default: 'Pending'
    },
    totalPrice: {
        type: Number
    },
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    dateOrdered: {
        type: Date,
        default: Date.now
    }
})

orderSchema.virtual('id').get(function () {   //This 2 functions allows to pass a virutal field
    return this._id.toHexString();      //this allows change specific things on the autogenerated fiels like ID.
});

orderSchema.set('toJSON', {       //dont replace the original data, just add a new one with the same value
    virtuals: true,
});

// Model of the product api

exports.Order = mongoose.model('Order', orderSchema);