const mongoose = require('mongoose');

const productSchema = mongoose.Schema({
    name: {
        type: String,
        required: true,
    },
    description: {
        type: String,
        required: true,
    },
    richDescription: {
        type: String,
        default: '',
    },
    image: {
        type: String,
        default: '',
    },
    images: [{
        type: String
    }],
    brand: {
        type: String,
        default: '',
    },
    price: {
        type: Number,
        required: true,
        default: 0
    },
    category: {
        type: mongoose.Schema.Types.ObjectId, //This is tha way to link the Category ID from the table of Category
        ref: 'Category',
        required: true
    },
    countInStock: {
        type: Number,
        required: true,
        min: 0,
        max: 255
    },
    rating: {
        type: Number,
        default: 0
    }, 
    numReviews: {
        type: Number,
        default: 0
    },
    isFeatured: {
        type: Boolean,
        default: false
    },
    dataCreated: {
        type: Date,
        default: Date.now,
    }
})

productSchema.virtual('id').get(function () {   //This 2 functions allows to pass a virutal field
    return this._id.toHexString();      //this allows change specific things on the autogenerated fiels like ID.
});

productSchema.set('toJSON', {       //dont replace the original data, just add a new one with the same value
    virtuals: true,
});

// Model of the product api and the export to be able to access in other files

exports.Product = mongoose.model('Product', productSchema);